backend/src/srsites/srsites.controller.ts
backend/src/srsites/srsites.service.ts
backend/utils/constants.ts
frontend/public/js/util.js
frontend/src/pay/pay.service.ts
frontend/src/site-registry/site-registry.controller.ts
frontend/src/site-registry/site-registry.service.ts
frontend/views/pages/address-search.hbs
frontend/views/pages/view-search-results.hbs

Changes to the view search results page columns and the data received from the backend on search. Also added more info dialogs to address search page.

Moesite 29

---

backend/src/srsites/srsites.controller.ts
backend/src/srsites/srsites.module.ts
backend/src/srsites/srsites.service.ts
frontend/public/js/util.js
frontend/src/bc-registry/bc-registry.controller.ts
frontend/src/bc-registry/bc-registry.service.ts
frontend/src/main.ts
frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/nilTemplate.html
frontend/utils/templates/synopsisTemplate.html
frontend/views/pages/index.hbs
frontend/views/pages/view-search-results.hbs

Add Nil Report which is downloadable when your search turns up nothing.

Nil template

---

backend/src/srsites/srsites.service.ts
frontend/src/bc-registry/bc-registry.service.ts

Small update to address search to accept * as any character. The search already looks for strings in the database 'like' the string provided, not specifically that string, so the * is simply trimmed out and the search is done normally. Also I reverted a change I made to fs template reading in local vs docker.

Address search update

---

frontend/Dockerfile

Trying to fix GitHub Actions frontend build

---

backend/src/srprofil/entities/srprofil.entity.ts
backend/utils/constants.ts

srprofil was out of date in the data dictionary, updated the entity to reflect actual columns

update srprofil entity

---

backend/src/srsites/srsites.controller.ts
backend/src/srsites/srsites.service.ts
frontend/public/js/util.js
frontend/src/bc-registry/bc-registry.controller.ts
frontend/src/bc-registry/bc-registry.service.ts
frontend/utils/templates/searchResultsPartialTemplate.html
frontend/utils/types.ts
frontend/views/pages/crown-lands-file.hbs
frontend/views/pages/site-id-search.hbs
frontend/views/pages/view-search-results.hbs

Add a button to the search results page that allows you to email the results.

Email search results

---

frontend/views/pages/crown-lands-pin.hbs

Pin search charlimit

---

frontend/public/js/util.js
frontend/src/app.controller.ts
frontend/src/authentication/authentication.guard.ts
frontend/src/authentication/authentication.service.ts
frontend/utils/types.ts
frontend/views/pages/view-search-results.hbs

- Added a modal for selecting from a list or inputting the email you wish to send search results or a report to.
- Added some search spinner logic to utils, made it active in search-spinners branch.

User account email

---

frontend/src/pay/pay.service.ts

Updated the file type codes used for all routes.

File type codes update

---

frontend/src/pay/pay.service.ts

There was a mismatch in file type codes for reports.

The report type codes were mismatched

---

backend/src/srsites/srsites.service.ts
frontend/public/css/custom.css
frontend/public/js/util.js
frontend/src/account/account.filter.ts
frontend/src/account/account.guard.ts
frontend/src/account/account.module.ts
frontend/src/app.controller.ts
frontend/src/authentication/authentication.controller.ts
frontend/src/authentication/authentication.filter.ts
frontend/src/authentication/authentication.guard.ts
frontend/src/authentication/authentication.module.ts
frontend/src/authentication/authentication.service.ts
frontend/src/bc-registry/bc-registry.controller.ts
frontend/src/site-registry/site-registry.controller.ts
frontend/utils/types.ts
frontend/views/pages/area-search.hbs
frontend/views/pages/index.hbs
frontend/views/partials/navbar.hbs

Users may have zero, one, or multiple active premium accounts. 
- If there are none, display an error message.
- If there is one, set it as the active account.
- If there are multiple accounts, prompt them to select one as the account to use.

detect and handle user accounts

---

backend/src/srsites/srsites.service.ts

Crown Lands File Number, Parcel ID, and Crown Lands PIN searches were only returning one site even if multiple were found.

CLF, PIN, PID search bugfix

---

backend/src/srsites/srsites.service.ts
frontend/src/bc-registry/bc-registry.service.ts

Quick fixes for MOESITE-61 and MOESITE-62
MOESITE-63 seems to already be working as intended

fix for 61/62

---

backend/utils/util.ts
frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/nilPdfTemplate.html
frontend/utils/templates/nilTemplate.html
frontend/utils/templates/searchResultsPartialTemplate.html
frontend/utils/templates/synopsisTemplate.html

Fix date issue, shifted date/time to the right, removed BC Online from the title on each report template

fix date issue, shift to right, remove bc online

---

frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/nilPdfTemplate.html
frontend/utils/templates/nilTemplate.html
frontend/utils/templates/searchResultsPartialTemplate.html
frontend/utils/templates/synopsisTemplate.html

Updated the report titles to include BC Registry

change BC Online to BC Registry in reports

---

backend/src/srassocs/entities/srassoc.entity.ts
backend/src/srdocpar/entities/srdocpar.entity.ts
backend/src/srevents/entities/srevent.entity.ts
backend/src/srevpart/entities/srevpart.entity.ts
backend/src/srlands/entities/srland.entity.ts
backend/src/srparrol/entities/srparrol.entity.ts
backend/src/srpinpid/entities/srpinpid.entity.ts
backend/src/srprfcat/entities/srprfcat.entity.ts
backend/src/srprfque/entities/srprfque.entity.ts
backend/src/srprfuse/entities/srprfuse.entity.ts
backend/src/srprofil/entities/srprofil.entity.ts
backend/src/srsitdoc/entities/srsitdoc.entity.ts
backend/src/srsites/entities/srsite.entity.ts
backend/src/srsitpar/entities/srsitpar.entity.ts

Data was not always staying within column size restrictions. This PR increases the size of many description columns.

greatly increase char limit on many columns

---

frontend/src/main.ts

testing deployment

---

backend/src/main.ts
frontend/src/main.ts

2 small changes to test deployment

---

.github/workflows/pr-open.yml

When cleaning up the old frontend image, the if statement was checking the backend instead of the frontend.

frontend clean image checks backend image

---

backend/test/app.e2e-spec.ts
frontend/test/app.e2e-spec.ts

Change to kickstart github actions

---

.github/openshift/deploy.backend.yml
backend/src/actions/dto/action.dto.ts
frontend/src/account/account.filter.ts

Removed duplicate object_store_bucket

---

frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/nilPdfTemplate.html
frontend/utils/templates/nilTemplate.html
frontend/utils/templates/searchResultsPartialTemplate.html
frontend/utils/templates/synopsisTemplate.html

Quick change to title and some alignments

another title change

---

backend/src/cron/cron.service.ts
backend/src/srprofil/entities/srprofil.entity.ts
frontend/src/authentication/authentication.service.ts

This should fix the cron job failing.

Increase Column Widths for srprofil entity

---

backend/src/cron/cron.service.ts
backend/src/srdate/srdates.controller.ts

Two small changes that should prevent the downloaddate issue

small change that should catch issue

---

backend/src/actions/dto/action.dto.ts
backend/src/cron/cron.service.ts
frontend/src/account/account.filter.ts

Reset updating status on backend startup

---

backend/src/srsites/srsites.service.ts

Simply count and display the number of associated sites attached to the site in the srassocs table

fix associated sites calculation

---

.github/workflows/pr-open.yml

Always build the frontend and the backend on PR open

always build frontend and backend

---

backend/src/cron/cron.service.ts
frontend/src/bc-registry/bc-registry.service.ts

Found a simple fix for the issue that was occurring.

Fix generation error for certain detail reports

---

backend/src/srsites/srsites.module.ts
backend/src/srsites/srsites.service.ts
frontend/src/bc-registry/bc-registry.service.ts

Add some additional sections to the detail report and fix some generating issues.

More dr updates

---

backend/.prettierignore
backend/src/srsites/srsites.service.ts
backend/utils/util.ts
frontend/.prettierignore
frontend/public/js/leaflet-src.js
frontend/public/js/util.js
frontend/src/bc-registry/bc-registry.service.ts
frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/nilPdfTemplate.html
frontend/utils/templates/nilTemplate.html
frontend/utils/templates/searchResultsPartialTemplate.html
frontend/utils/templates/synopsisTemplate.html
frontend/utils/util.ts

- Changed many titles
- Added disclaimer to each report
- Added Site Profile information to Synopsis Report
- Added logic around the 2021-02-01 date
- Small update to how a leaflet function is called
- Display multiple sorted site profiles in Detail Report, display only most recent in Synopsis Report
- Remove status and fee category from both reports

SITE 330,331,332+

---

backend/src/cron/cron.service.ts
backend/src/srprofil/entities/srprofil.entity.ts
backend/src/srsites/srsites.service.ts
backend/utils/constants.ts
backend/utils/util.ts
frontend/public/js/util.js
frontend/src/bc-registry/bc-registry.service.ts
frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/nilPdfTemplate.html
frontend/utils/templates/nilTemplate.html
frontend/utils/templates/searchResultsPartialTemplate.html
frontend/utils/templates/synopsisTemplate.html
frontend/utils/util.ts

- Change all fonts in the reports to Arial
- Don't display questions which haven't been answered
- Various changes to titles and strings
- Added more logic around the 2021-02-01 date when it comes to certain titles
- Made dividing lines more consistent (black between sections, grey inside sections)
- Small formatting updates to nil reports
- Found bug where dateCompleted and dateReceived were swapped in Srprofil table
- Greatly increased the speed that tables delete their old data when updating.

many more changes

---

backend/src/srsites/srsites.service.ts
frontend/src/bc-registry/bc-registry.service.ts

Srprofil data was being sorted by dateCompleted as opposed to dateReceived leading to the order of site profiles being incorrect sometimes. Also added logic to ensure the site profile/site disclosure statement always has a title.

sorting issue and title issue

---

backend/utils/util.ts
frontend/src/bc-registry/bc-registry.service.ts

- Changed the current date string on all reports
- Updated the headers in the Additional Comments and Explanations section
- Update font size of "End of Report" string
- Remove extra "Radius" from search results report

fixes for initial QAT findings

---

frontend/src/bc-registry/bc-registry.service.ts
frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/searchResultsPartialTemplate.html
frontend/utils/templates/synopsisTemplate.html

There were occasionally large gaps at the start of the site profile section, it seems to be an artifact caused by the pdf generator. Added a hidden divider that should prevent the gap.

try to prevent large gaps

---

backend/src/srsites/srsites.service.ts

There was a query inside of a loop causing the database to be queried 200+ times. Changed the query and moved it outside of the loop.

Potential fix for the site 89 report issues

---

frontend/src/authentication/authentication.guard.ts
frontend/src/site-registry/site-registry.service.ts

Check if user has logged out when accessing main page

---

.github/openshift/deploy.frontend.yml
frontend/src/bc-registry/bc-registry.service.ts

parameterized cdogs/ches urls

---

frontend/views/pages/area-search.hbs
frontend/views/pages/index.hbs
frontend/views/pages/site-id-search.hbs

change displayed price on all pages

---

frontend/src/bc-registry/bc-registry.service.ts

CDOGS token and CHES token are now acquired and used separately.
PR the size it is because prettier reformatted some of the code.

cdogs and ches token are now separate

---

frontend/Dockerfile

Adding chmod

---

frontend/Dockerfile

back to entrypoint

---

frontend/utils/templates/detailedPartialTemplate.html
frontend/utils/templates/detailedPartialTemplate.html.bak
frontend/utils/templates/synopsisTemplate.html.bak

template reversion

---

frontend/src/bc-registry/bc-registry.service.ts

- Updated the timeout for puppeteer

update the puppeteer timeout

---

.github/openshift/deploy.database.yml
.github/openshift/deploy.frontend.yml

Resources increase for backend and database

---

backend/src/srsites/srsites.controller.ts
backend/utils/util.ts
frontend/src/bc-registry/bc-registry.controller.ts
frontend/utils/templates/synopsisTemplate.html
frontend/utils/util.ts

There was a small formatting issue in the synopsis report

noticed formatting issue in synopsis

---

frontend/views/pages/address-search.hbs
frontend/views/pages/area-search.hbs
frontend/views/pages/crown-lands-file.hbs
frontend/views/pages/crown-lands-pin.hbs
frontend/views/pages/index.hbs
frontend/views/pages/parcel-id.hbs
frontend/views/pages/site-id-search.hbs
frontend/views/pages/view-search-results.hbs

Change a string in the breadcrumb

business search -> site registry

---

backend/src/srsites/srsites.controller.ts
frontend/src/authentication/authentication.guard.ts
frontend/src/bc-registry/bc-registry.controller.ts

A blank folio field was causing issues

make sure that folio is never null

---

.github/openshift/deploy.backend.yml
.github/openshift/deploy.database.yml
.github/openshift/deploy.frontend.yml

further update to resources
